#!/bin/bash
hora=`date +"%H"`
if [ $hora -lt 13 ];then
    mensagem="Buenos Dias"
elif [ $hora -gt 12 -a $hora -lt 20 ]; then
    mensagem="Buenas Tardes"
else
    mensagem="Buenas noches"
fi

x="teste"
menu ()
{
while true $x != "teste"
do
clear
#rm -rf /data/data/com.termux/files/home/instalador
v="\033[0;31m"
b="\033[1;37m"
a="\033[1;32m"
A="\033[1;36m"
c="\033[5;31m"
port="8080"
#echo -e "\033[5;31mteste\033[1;37m"
ip=$(ifconfig | awk -F: '/inet addr/ { print $2 } '| sed s/Bcast//g | sed s/Mask//g | sed s/P-t-P//g | sed '1d')
#nome=$(cat /data/data/com.termux/files/home/user)
pp()
                    {
                    echo -e "
      [*] $a Recuerda tienes que configurar el wifi del telefono que se conecta. En la parte de Wifi, selecciona la Red, en ajustes - Mostrar opciones avanzadas - En proxy seleciona Manual - En el proxy escribe la IP que aparece en pantalla y en puerto el que seleccionaste$b "
      echo -e "
      
      "
     printf '%s\n' $ip
    echo -e "
    
    "
    sleep 5
    echo Enter Para Continuar
    read a
     printf '%s\n' $ip | while read p
     do
     sleep 2
     python /data/data/com.termux/files/usr/bin/routec.cpython-37.pyc --hostname $p --port $port &
     done
      
      read a 
               }
                    echo -e "\033[0;34m=============================================\033[01;37m"
echo ""
echo -e "              \033[1;36mRoute script\033[1;37m"
echo ""
echo -e "\033[0;34m
=============================================\033[01;37m"

echo -e "Curso Termux : \033[5;31mEl conocimiento es libre\033[1;37m"
echo -e "$mensagem \033[1;33m$nome\033[1;37m"
echo ""
echo -e "\033[1;32m[ 1 ]\033[1;37m \033[1;36mCompartir Internet VPN$b"
echo""
echo""
echo -e "\033[1;32m[ 5 ]$b \033[1;36mSalir\033[1;37m"
echo ""
echo -e "\033[0;34m
==============================================\033[01;37m"

echo "Digite el numero deseado:"
read x
echo -e "opcion Informada ($v$x$b)"
echo -e "\033[0;34m
=============================================\033[01;37m"

case "$x" in 


    1)
    echo -e "Puerto que desea utilizar\nLe recomiendo el 8080"
      echo -e "
    #  [*] $a Ok connect $escolha  $escolha2 $b "
      echo -e "
                         
                         "
                         read port
    [[ $port -gt 1024 ]] && pp || echo -e "Puerto Incorrecto\n Escriba un puerto mayor a 1024" && exit
      
echo -e "\033[0;34m
===============================================\033[01;37m"
;;
       
     5)  
       echo "saindo..."
       sleep 5
       clear;
    killall python
       killall -s SIGINT python
clear
       exit;
echo "================================================"
;;

*)
    echo -e "\033[1;36mOpcion Incorrecta\033[1;37m"
        sleep 5
esac
done

}
menu
